Repository zwjddn1105/JavaScript-Python-Algorithm, pull requests merged in 2025-01, with the labels that each got.

#7 BOJ_11720
  week1/KJW/BOJ_11720.js
Labels: 코드리뷰대기중

#6 A+B-3, 숫자의 합
  week1/ee/B10950.js
  week1/ee/B11729.js
  week1/ee/tc.txt
Labels: 코드리뷰대기중

#8 BOJ_10950, BOJ_11720
  week1/hs/BOJ_10950.js
  week1/hs/BOJ_11720.js
Labels: 코드리뷰대기중, 코드리뷰 완료

#9 20250116
  week1/KJW/BOJ_10818.js
  week1/KJW/BOJ_1152.js
Labels: 코드리뷰대기중

#10 최소,최대 + 단어의 개수
  week1/ee/B10818.js
  week1/ee/B1152.js
  week1/ee/tc.txt
Labels: 코드리뷰대기중

#11 BOJ_1152, BOJ_10818
  week1/hs/BOJ_10818.js
  week1/hs/BOJ_1152.js
Labels: 코드리뷰 완료

#12 무지의먹방라이브
  week1/KJW/무지의먹방라이브.py
  week2/BOJ_1026.js
Labels: 코드리뷰대기중

#15 feat(BOJ 1026) 2주차 1026 보물_aaange
  week2/aaange/1026.js
  week2/aaange/1026.py
Labels: 코드리뷰대기중

#13 BOJ_1026, BOJ_1159(js, py)
  week2/hs/BOJ_1026.js
  week2/hs/BOJ_1159.js
  week2/hs/BOJ_1159.py
Labels: 코드리뷰대기중

#16 [2주차] 보물, 농구경기
  week2/ee/input.txt
  week2/ee/농구경기.js
  week2/ee/농구경기.py
Labels: 코드리뷰 완료

#17 [2주차] 폴리오미노, 1로만들기, 분산처리, 더하기사이클
  week2/README.md
  week2/ee/1로만들기.js
  week2/ee/더하기사이클.js
  week2/ee/더하기사이클.py
  week2/ee/보물.js
  week2/ee/분산처리.js
  week2/ee/폴리오미노.js
  week2/ee/폴리오미노.py
Labels: 코드리뷰 완료

#14 BOJ_1159 -js, py
  week1/KJW/무지의먹방라이브.py
  week2/KJW/BOJ_1009.js
  week2/KJW/BOJ_1026.js
  week2/KJW/BOJ_1110.js
  week2/KJW/BOJ_1110.py
  week2/KJW/BOJ_1159.js
  week2/KJW/BOJ_1159.py
  week2/KJW/BOJ_1343.js
  week2/KJW/BOJ_1463.js
  week2/KJW/input.txt
Labels: 코드리뷰대기중
